"""services

Revision ID: 6647bf812d91
Revises: 545e00abc28c
Create Date: 2024-07-30 07:07:11.312850

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from apps.services.schema.services import Service
from services.postgres.models import ServicesModel
from utils.logger import get_logger

# revision identifiers, used by Alembic.
revision: str = '6647bf812d91'
down_revision: Union[str, None] = '545e00abc28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = get_logger("MIGRATOR")

services: list[Service] = []


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for service in services:
        try:
            query = sa.insert(ServicesModel).values(**service.model_dump(mode='json'))
            op.execute(query)
        except Exception as error:
            logger.error(error)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for service in services:
        try:
            query = sa.delete(ServicesModel).where(ServicesModel.name == service.name)
            op.execute(query)
        except Exception as error:
            logger.error(error)
    # ### end Alembic commands ###
